### ISSUE TITLE
Multiple inputs/outputs

### ISSUE THREAD

**Issue by jazz-soft** [micbuffa/WebAudioPlugins#3]
A QUESTION:

How do the API calls look for multiple inputs/outputs?

e.g. if device1 has 1 output and device2 has 1 input, we can call
`device1.connect(device2);`

if the devices have several inputs/outputs, how do we connect 
the 2nd output from the device1 to the 3rd input of the device2 ?

And any suggestions of how the API should address MIDI inputs/outputs ?

**Comment by micbuffa** [comment]
Just conform to the WebAudio spec. We implemented the spec. From memory var destinationNode = AudioNode.connect(destination, outputIndex, inputIndex);

AudioNode.connect(destination, outputIndex);

See: https://developer.mozilla.org/en-US/docs/Web/API/AudioNode/connect

I found the bug about multiple instances. Not an easy one to fix. Will do my best to fix it today. Thanks a lot for spotting it... It works when you have a multiple set of plugins, the bug comes in the promise that creates the link rel=import href=url for the WebComponent, instead of blocking until the html file has been loaded completely, it resolves earlier, so when you do the second call to loadGUI for the second instance, as the link has not loaded its file completely, it breaks. I have a promise and an onload inside (see loadGUi code). I need to change the algorithms and be sure that we don't try to create a second instance before the link is not 100% complete. Will find the solution as soon as possible.

**Comment by jazz-soft** [comment]
How do you prefer to do MIDI connections in the new API? I see 3 possibilities:

1) same as audio, device1.connect(device2, index1, index2); - we need to remember which index corresponds to MIDI and which corresponds to Audio, and make sure they are of the same type.

2) index MIDI and Audio inputs/outputs separately, and call different function, e.g.  device1.connectMidi(device2, ...);

3) you may have some better ideas...

I have a couple of simple MIDI devices in my branch, and ready to implement connections.

**Comment by micbuffa** [comment]
I'd prefer solution number 2 I think... then, with your solution, midi events will be sent asynchronously from source to dest ? I only know how the WebMidi API works with the onMidiMessage listeners, etc... The idea of "routing" midi is to make direct connections. So far in our  plugins, each plugins can implement support for a midi keyboard (select from drop down menu), but I'd like to be able to route a sort of "global host defined midi input" too (imagine on the left another input with another color), if you connect a synth to the global midi input, then it will be connected to midi devices defined at the host level. If you connect a synth to another one you do midi chaining, an arpegiattor to a synth, you are also routing a midi emitter to a midi receiver... That's how I imagine this, but I'm not a MIDI guy, you are certainly much more an expert than I :-)
But I prefer not to alter the semantic of the AudioNode interface by altering connect/disconnect.

Michel

**Comment by jazz-soft** [comment]
Ok, I'll go with option 2.

BTW, are you planning to make WebAudioPlugins work with Firefox/Edge?

**Comment by micbuffa** [comment]
Yes, of course, the main problem is: 1) there is no support for AudioWorklets yet in these browsers, so Faust plugins won't work, WAM plugins won't work and 2) (more problematic): there is no support for the way we add WebComponents (using a `<link rel="import" href="http://...../main.html">` that is not supported yet by any other browser than Chrome, and that might change as the WebComponent working group did not agree yet on a proper way to do this... ES6 modules is certainly the way that will be chose, but unfortunately there is yet no consensus on the way WebComponent files should be imported. I'll be at the TPAC conference the next week and will talk with people from these W3C working groups and with people from Edge, FF etc. I'm in the W3C WebAudio working group. As soon as there is a standard way to import web components, we'll update the SDK. If there is a workaround we'll take it into account too. There is an official javascript polyfill but unfortunately it does not work when we create the `<link rel="import" href="http://...../main.html">` on the fly programmatically. Maybe there is a way to activate the polyfill as soon as we create this html element, or to create instead the code the polyfill generates... I'll ask experts aout this the next week.

**Comment by jazz-soft** [comment]
I have MIDI connections working. Please have a look at my fork.
I want to implement a couple more MIDI nodes before creating a pull request.

**Comment by micbuffa** [comment]
WOW, this looks so... clean and simple :-) And it works pretty well! I gave a very quick look to the code and it seems very clear. I will have more time this afternoon to give you detailed feedback but it looks pretty good. We will have to think about what to put on the SDK and what to leave as is (the midi in/out for example, should be declared in a way through the SDK so that hosts can "ask plugins" about their number of midi I/0s, etc. JJZ might be included at the host level as a global dependency too, for the moment... I really like the fact that you packaged your piano, synth and monitor as WebAudio Plugins...

For me, here are the steps I'm  gonna do:

- Look  at your code

- Try to use for example your piano with another synth (not one of yours, one we'll modify) in a simple tester

- Try to publish your plugins (give them URIs on a real remote server)

- Try to load them in the testers (even if they do not pass the tests)

- Try to load them in the pedalboard

- Update the pedalboard to be able to draw "midi wires" between midi plugins

**Comment by micbuffa** [comment]
Can we organize a visio the next week ? Send me email buffa@unice.fr thanks !
